apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [{
             "resourceName": "mlnx_sriov_rdma",
             "resourcePrefix": "mellanox.com",
             "rdmaHcaMax": 1,
             "devices": ["ib0"]
           }]
    }