# modified from source: https://github.com/Mellanox/k8s-rdma-shared-dev-plugin

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rdma-shared-dp-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: rdma-shared-dp-ds
  template:
    metadata:
      labels:
        name: rdma-shared-dp-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - Standard_H16mr
                - Standard_H16mr_Promo
                - Standard_H16r
                - Standard_H16r_Promo
                - Standard_H8_Promo
                - Standard_HB120-16rs_v2
                - Standard_HB120-32rs_v2
                - Standard_HB120-64rs_v2
                - Standard_HB120-96rs_v2
                - Standard_HB120rs_v2
                - Standard_HB120-16rs_v3
                - Standard_HB120-32rs_v3
                - Standard_HB120-64rs_v3
                - Standard_HB120-96rs_v3
                - Standard_HB120rs_v3
                - Standard_HB60-15rs
                - Standard_HB60-30rs
                - Standard_HB60-45rs
                - Standard_HB60rs
                - Standard_NC24rs_v2
                - Standard_ND96amsr_A100_v4
                - Standard_ND96asr_v4
                - Standard_HC44rs
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
      - image: mellanox/k8s-rdma-shared-dev-plugin
        name: k8s-rdma-shared-dp-ds
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/
          - name: config
            mountPath: /k8s-rdma-shared-dev-plugin
          - name: devs
            mountPath: /dev/
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/
        - name: config
          configMap:
            name: rdma-devices
            items:
            - key: config.json
              path: config.json
        - name: devs
          hostPath:
            path: /dev/
