apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name install-mlx-driver
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - standard_hb120rs_v2
                - Standard_HB120rs_v3
                - Standard_HB60rs
                - Standard_HC44rs
      hostNetwork: true
      hostPID: true
      containers:
      - image: docker.io/lilypan26/install-mellanox-driver:latest # aksrdma.azurecr.io/lilypan/install-ibdriver:latest # TODO: build me! # requires an image with bash, curl, sleep, and nsenter (vanilla ubuntu works)
        imagePullPolicy: Always
        name: *name
        command: ["/entrypoint.sh"] # can reuse from fpga example
        args: ["installonly"] # if you don't use my image or build one from Dockerfile, set this to "downloadandinstall"
        resources:
          requests:
            {}
          limits:
            {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: actions
          mountPath: "/opt/actions"
        - name: hostmount
          mountPath: "/mnt/actions"
        - name: debs
          mountPath: "/mnt/debs"
      volumes:
      - name: debs
        hostPath:
          path: /opt/debs
          type: DirectoryOrCreate
      - name: hostmount
        hostPath:
          path: /opt/actions
          type: DirectoryOrCreate
      - name: actions
        configMap:
          name: install-actions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install-actions
  labels:
    app: install
data:
  installonly: |
    #!/usr/bin/env bash
    set -eo pipefail

    # This script should be executed on VM host in the directly as the deb 
    # will install systemd units and host dependencies.

    SECONDS=0
    ## TODO: add mount iso ++ install drivers ++ some quick validation with e.g ibstat?
    apt install -y pciutils
    pciBusID=$(lspci -v | grep Infiniband | head -n1 | awk '{print $1;}')
    echo $pciBusID
    export pciBusID
    printenv

    cd /opt/debs
    mount -o ro,loop MLNX_OFED_LINUX-5.6-2.0.9.0-ubuntu18.04-x86_64.iso /mnt
    /mnt/mlnxofedinstall --force -v
    /etc/init.d/openibd restart
    set -x

    check_ib="$(ip link | grep ib0)"

    if [ -z "$check_ib" ];
    then
      echo "driver installation failed"
    else
      echo "driver installation successful"
    fi
    echo "installation completed in $SECONDS seconds"
    

  downloadandinstall: |
    #!/usr/bin/env bash
    set -eo pipefail

    # TODO add iso download -- good for testing on ubuntu 20.04 without rebuilding an image
    apt update && apt install -y curl
    curl -L https://content.mellanox.com/ofed/MLNX_OFED-5.6-2.0.9.0/MLNX_OFED_LINUX-5.6-2.0.9.0-ubuntu18.04-x86_64.iso -o MLNX_OFED_LINUX-5.6-2.0.9.0-ubuntu18.04-x86_64.iso

    pciBusID=$(lspci -v | grep Infiniband | head -n1 | awk '{print $1;}')
    export pciBusID

    mount -o ro,loop MLNX_OFED_LINUX-5.6-2.0.9.0-ubuntu18.04-x86_64.iso /mnt
    /mnt/mlnxofedinstall --force -v
    /etc/init.d/openibd restart
    set -x

    check_ib="$(ip link | grep ib0)"

    if [ -z "$check_ib" ];
    then
      echo "driver installation failed"
    else
      echo "driver installation successful"
    fi    
---
