apiVersion: v1
kind: ConfigMap
metadata:
  name: install-script
  namespace: kube-system
data:
  install-script.sh: |
    #!/usr/bin/env bash

    set -euo pipefail
    set -x

    install_containerd() {
      local need_download

      need_download=$(/host/usr/bin/containerd -version 2>/dev/null | grep 2.2.1 || echo true)
      if [[ "${need_download}" != "true" ]]; then
        echo "the current containerd version"
        /host/usr/bin/containerd -version
        return
      fi

      apt update -y
      apt install wget -y

      wget https://github.com/containerd/containerd/releases/download/v2.2.1/containerd-static-2.2.1-linux-amd64.tar.gz
      tar -xvf ./containerd-static-2.2.1-linux-amd64.tar.gz

      install_dir="/host/usr/bin"
      target_files="ctr containerd containerd-shim containerd-shim-runc-v1 containerd-shim-runc-v2"
      for target in ${target_files}; do
        install "./bin/${target}" "${install_dir}/${target}"
      done
    }

    install_runc() {
      local need_download

      need_download=$(/host/usr/bin/runc -version 2>/dev/null | grep 1.4.0 || echo true)
      if [[ "${need_download}" != "true" ]]; then
        echo "the current runc version"
        /host/usr/bin/runc -version
        return
      fi

      wget https://github.com/opencontainers/runc/releases/download/v1.4.0/runc.amd64
      install ./runc.amd64 /host/usr/bin/runc
      chmod 755 /host/usr/bin/runc
    }

    install_containerd
    install_runc
    chroot /host bash -c "systemctl restart containerd"
    sleep 15s
    chroot /host bash -c "crictl info"
    sleep infinity