apiVersion: v1
kind: Pod
metadata:
  name: rdma-pod1
  # annotations:
  #   k8s.v1.cni.cncf.io/networks: macvlan-net1 
spec:
  containers:
  - name: mofed-test-ctr
    image: mellanox/rping-test
    securityContext:
     capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        mellanox.com/shared_hca_rdma: 1
      limits:
        mellanox.com/shared_hca_rdma: 1
    command: ["sleep", "infinity"]
  # nodeName: aks-rdmanp-17508136-vmss000000 # For testing purposes if you want to force pods to be on same node in shared hca mode. Change to your node name or comment out if not needed.
  #terminatoingraceperiod:0
---
apiVersion: v1
kind: Pod
metadata:
  name: rdma-pod2
  # annotations:
  #   k8s.v1.cni.cncf.io/networks: macvlan-net1
spec:
  containers:
  - name: mofed-test-ctr
    image: mellanox/rping-test
    securityContext:
     capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        mellanox.com/shared_hca_rdma: 1
      limits:
        mellanox.com/shared_hca_rdma: 1
    command: ["sleep", "infinity"]
  # nodeName: aks-rdmanp-17508136-vmss000001  # For testing purposes if you want to force pods to be on same node in shared hca mode. Change to your node name or comment out if not needed.