apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_sriov_rdma",
                "resourcePrefix": "mellanox.com",
                "selectors": {
                    "isRdma": true
                }
            }
        ]
    }
