apiVersion: mellanox.com/v1alpha1
kind: IPoIBNetwork
metadata:
  name: aks-infiniband
spec:
  networkNamespace: "default"
  # This is an alt interface name for the IPoIB interface. As per this blog it
  # seems to be common across the same VM SKU:
  # https://techcommunity.microsoft.com/blog/azurehighperformancecomputingblog/running-tightly-coupled-hpcai-workloads-with-infiniband-using-nvidia-network-ope/4117209
  # It has been consistent on the machine types: Standard_HB120rs_v3 and Standard_ND96asr_v4.
  # TODO: Figure out how to get this generic name?
  master: "ibP257p0s0"
  ipam: |
    {
      "type": "whereabouts",
      "datastore": "kubernetes",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
      },
      "range": "192.168.0.0/16",
      "exclude": [
       "192.168.0.0/32",
       "192.168.255.255/32"
      ],
      "log_file" : "/var/log/whereabouts.log",
      "log_level" : "info",
      "gateway": "192.168.0.1"
    }
