# Versions are provided at: https://docs.nvidia.com/networking/display/kubernetes<driver-version>/platform-support.html
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: aks-nic-cluster-policy
spec:
  rdmaSharedDevicePlugin:
    repository: ghcr.io/mellanox
    image: k8s-rdma-shared-dev-plugin
    # Latest tag: https://github.com/mellanox/k8s-rdma-shared-dev-plugin/pkgs/container/k8s-rdma-shared-dev-plugin
    version: v1.5.2
    useCdi: true
    # The config below directly propagates to k8s-rdma-shared-device-plugin configuration.
    # Replace 'devices' with your (RDMA capable) netdevice name.
    config: |
      {
        "configList": [
          {
            "resourceName": "rdma_shared_device_a",
            "rdmaHcaMax": 63,
            "selectors": {
              "vendors": ["15b3"], # Mellanox
            }
          }
        ]
      }
