name: benchmark-container-image

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: azure/aks-rdma-infiniband
  IMAGE_NAME: benchmark

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/benchmark-image.yml'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/benchmark-image.yml'
      - 'Dockerfile'

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build and push Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'Azure/aks-rdma-infiniband' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
