name: Build & Push Infiniband Tools Container Image

on:
  push:
    paths:
      - tests/containers/ibtools/Dockerfile
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate tags
      id: tag
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/Azure/aks-rdma-infiniband/ibtools
        tags: |
          type=raw,value=latest
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='America/Los_Angeles'}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: tests/containers/ibtools
        file: tests/containers/ibtools/Dockerfile
        push: true
        tags: ${{ steps.tag.outputs.tags }}
        labels: ${{ steps.tag.outputs.labels }}
